use testDB;
Insert into customer(name, address, phone_number, email) values('Simon', '64 Zoo Lane', 0789236789, 'kin@inbox.com' );
Insert into customer(name, address, phone_number, email) values('Bruce', '87 Ivy Road', 0761436781, 'gotham@batbox.com' );
Insert into customer(name, address, phone_number, email) values('Amanda', '12 Gunners Street', 0752961123, 'kin@inbox.com' );
Insert into customer(name, address, phone_number, email) values('Susan', '19 Barnay Street', 0752346123, 'Susie@inbox.com' );
Insert into items(item, quantity,price)values('The Great Gatsby',200,29.99);
Insert into items(item, quantity,price)values('The Wind in the Willows',90,9.99);
Insert into items(item, quantity,price)values('Peter Pan',130,19.50);
Insert into items(item, quantity,price)values('Da vinci Code',10,20.00);
Insert into orders(fk_customer_id) values(3);
Insert into orders(fk_customer_id) values(2);
Insert into orders(fk_customer_id) values(1);
Insert into orderline(fk_order_id,fk_item_id, qty_ordered) values(2, 3,8);
Insert into orderline(fk_order_id,fk_item_id, qty_ordered) values(1, 1,1);